//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen_SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities4 : DbContext
    {
        public Database1Entities4()
            : base("name=Database1Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attraction> Attractions { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dolcnost> Dolcnosts { get; set; }
        public virtual DbSet<HistoryTour> HistoryTours { get; set; }
        public virtual DbSet<HistoryVisitCountry> HistoryVisitCountries { get; set; }
        public virtual DbSet<InterestingTour> InterestingTours { get; set; }
        public virtual DbSet<PayTour> PayTours { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudniks { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<Tourist> Tourists { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
