//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Clients = new HashSet<Client>();
            this.HistoryTours = new HashSet<HistoryTour>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int TransportId { get; set; }
        public int HistoryVisitCountryId { get; set; }
        public int AttractionsId { get; set; }
        public string UrlImageAttractions { get; set; }
        public string Description { get; set; }
        public string UrlImagehotel { get; set; }
        public int MaxClients { get; set; }
        public int SotrId { get; set; }
        public int PayTourId { get; set; }
        public int InterestingTourId { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryTour> HistoryTours { get; set; }
        public virtual HistoryVisitCountry HistoryVisitCountry { get; set; }
        public virtual InterestingTour InterestingTour { get; set; }
        public virtual PayTour PayTour { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
